import Head from 'next/head';
import Main from './main';
// import styles from '../src/styles/globalStyle';

export default function Home() {
  return (
    <>
      <Head>
        <title>우유부단</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Main />
      </main>
    </>
  );
}
